language: node_js
node_js:
  - "6"
  - "5"
  - "4"
  - "0.12"

# a compiler must be installed for libxmljs
# https://docs.travis-ci.com/user/languages/javascript-with-nodejs#Node.js-v4-(or-io.js-v3)-compiler-requirements
env:
  - CXX=g++-4.8
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.8
